/***********************************************************************/
/*                                                                     */
/*  FILE        :vecttbl.c                                             */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  

#include	<stdio.h>
#include    <machine.h>

#include    "iodefine.h"
#include    "vect.h"
		
#pragma section VECTTBL
void *RESET_Vectors[] = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset 
	PowerON_Reset                                                                                                                           
//;<<VECTOR DATA END (POWER ON RESET)>>
};
#pragma section INTTBL
void *INT_Vectors[] = {
	// 1 Reserved
	(void *) Dummy,
	// 2 Reserved
	(void *) Dummy,
	// 3 Reserved
	(void *) Dummy,
	// 4 Reserved
	(void *) Dummy,
	// 5 Reserved 
	(void *) Dummy,
	// 6 Reserved
	(void *) Dummy,
	// 7 NMI 
	(void *) INT_NMI,
	// 8 TRAP
	(void *) INT_TRAP1,
	// 9 TRAP
	(void *) INT_TRAP2,
	// 10 TRAP
	(void *) INT_TRAP3,
	// 11 TRAP
	(void *) INT_TRAP4,
	// 12 IRQ0
	(void *) INT_IRQ0,
	// 13 IRQ1
	(void *) INT_IRQ1,
	// 14 IRQ2
	(void *) INT_IRQ2,
	// 15 IRQ3
	(void *) INT_IRQ3,
	// 16 IRQ4
	(void *) INT_IRQ4,
	// 17 IRQ5
	(void *) INT_IRQ5,
	// 18 Reserved
	(void *) Dummy,
	// 19 Reserved
	(void *) Dummy,
	// 20 WOVI
	(void *) INT_WOVI,
	// 21 CMI
	(void *) INT_CMI,
	// 22 Reserved
	(void *) Dummy,
	// 23 Reserved
	(void *) Dummy,
	// 24 IMIA0
	(void *) INT_IMIA0,
	// 25 IMIB0
	(void *) INT_IMIB0,
	// 26 OVI0
	(void *) INT_OVI0,
	// 27 Reserved
	(void *) Dummy,
	// 28 IMIA1
	(void *) INT_IMIA1,
	// 29 IMIB1
	(void *) INT_IMIB1,
	// 30 OVI1
	(void *) INT_OVI1,
	// 31 Reserved
	(void *) Dummy,
	// 32 IMIA2
	(void *) INT_IMIA2,
	// 33 IMIB2
	(void *) INT_IMIB2,
	// 34 OVI2
	(void *) INT_OVI2,
	// 35 Reserved
	(void *) Dummy,
	// 36 IMIA3
	(void *) INT_IMIA3,
	// 37 IMIB3
	(void *) INT_IMIB3,
	// 38 OVI3
	(void *) INT_OVI3,
	// 39 Reserved
	(void *) Dummy,
	// 40 IMIA4
	(void *) INT_IMIA4,
	// 41 IMIB4
	(void *) INT_IMIB4,
	// 42 OVI4
	(void *) INT_OVI4,
	// 43 Reserved
	(void *) Dummy,
	// 44 DEND0A
	(void *) INT_DEND0A,
	// 45 DEND0B
	(void *) INT_DEND0B,
	// 46 DEND1A
	(void *) INT_DEND1A,
	// 47 DEND1B
	(void *) INT_DEND1B,
	// 48 Reserved
	(void *) Dummy,
	// 49 Reserved
	(void *) Dummy,
	// 50 Reserved
	(void *) Dummy,
	// 51 Reserved
	(void *) Dummy,
	// 52 ERI0
	(void *) INT_ERI0,
	// 53 RXI0
	(void *) INT_RXI0,
	// 54 TXI0
	(void *) INT_TXI0,
	// 55 TEI0
	(void *) INT_TEI0,
	// 56 ERI1
	(void *) INT_ERI1,
	// 57 RXI1
	(void *) INT_RXI1,
	// 58 TXI1
	(void *) INT_TXI1,
	// 59 TEI1
	(void *) INT_TEI1,
	// 60 ADI
	(void *) INT_ADI
};


extern	void	(*IRQ5Jump)(void);
extern	void	(*IRQ4Jump)(void);
extern	void	(*IRQ0Jump)(void);
extern	void	(*IMIA0Jump)(void);
extern		void	(*ERI0Jump)(void);
extern		void	(*RXI0Jump)(void);
extern	void	(*TXI0Jump)(void);
extern	void	(*TEI0Jump)(void);
extern	void	(*ERI1Jump)(void);
extern	void	(*RXI1Jump)(void);
extern	void	(*TXI1Jump)(void);
extern	void	(*TEI1Jump)(void);

#pragma section IntPRG
//  vector 1 Reserved

//  vector 2 Reserved

//  vector 3 Reserved

//  vector 4 Reserved

//  vector 5 Reserved 

//  vector 6 Reserved

//  vector 7 NMI 
void    INT_NMI(void) {/* sleep(); */}
//  vector 8 TRAP
void    INT_TRAP1(void) {/* sleep(); */}
//  vector 9 TRAP
void    INT_TRAP2(void) {/* sleep(); */}

//  vector 12 IRQ0
void    INT_IRQ0(void) {
		if( IRQ0Jump!=NULL ){
			IRQ0Jump();
		}
		else {
			INTC.ISR.BIT.IRQ0F = 0;
		}
}
//  vector 13 IRQ1
void    INT_IRQ1(void) {/* sleep(); */}
//  vector 14 IRQ2
void    INT_IRQ2(void) {/* sleep(); */}
//  vector 15 IRQ3
void    INT_IRQ3(void) {/* sleep(); */}
//  vector 16 IRQ4
void    INT_IRQ4(void) {
		if( IRQ4Jump!=NULL ){
			IRQ4Jump();
		}
		else {
			INTC.ISR.BIT.IRQ4F = 0;
		}
}
//  vector 17 IRQ5
void    INT_IRQ5(void) {
		if( IRQ5Jump!=NULL ){
			IRQ5Jump();
		}
		else {
			INTC.ISR.BIT.IRQ5F = 0;
		}
}
//  vector 18 Reserved

//  vector 19 Reserved

//  vector 21 CMI
void    INT_CMI(void) {/* sleep(); */}
//  vector 22 Reserved

//  vector 23 Reserved

//  vector 24 IMIA0
void    INT_IMIA0(void) {
		if( IMIA0Jump!=NULL ){
			IMIA0Jump();
		}
		ITU0.TSR.BIT.IMFA = 0;		/* タイマー割り込みクリア */
}

//  vector 25 IMIB0
void    INT_IMIB0(void) {/* sleep(); */}
//  vector 26 OVI0
void    INT_OVI0(void) {/* sleep(); */}
//  vector 27 Reserved

//  vector 28 IMIA1
void    INT_IMIA1(void) {/* sleep(); */}
//  vector 29 IMIB1
void    INT_IMIB1(void) {/* sleep(); */}
//  vector 30 OVI1
void    INT_OVI1(void) {/* sleep(); */}
//  vector 31 Reserved

//  vector 32 IMIA2
void    INT_IMIA2(void) {/* sleep(); */}
//  vector 33 IMIB2
void    INT_IMIB2(void) {/* sleep(); */}
//  vector 34 OVI2
void    INT_OVI2(void) {/* sleep(); */}
//  vector 35 Reserved

//  vector 36 IMIA3
void    INT_IMIA3(void) {/* sleep(); */}
//  vector 37 IMIB3
void    INT_IMIB3(void) {/* sleep(); */}
//  vector 38 OVI3
void    INT_OVI3(void) {/* sleep(); */}
//  vector 39 Reserved

//  vector 40 IMIA4
void    INT_IMIA4(void) {/* sleep(); */}
//  vector 41 IMIB4
void    INT_IMIB4(void) {/* sleep(); */}
//  vector 42 OVI4
void    INT_OVI4(void) {/* sleep(); */}
//  vector 43 Reserved

//  vector 44 DEND0A
void    INT_DEND0A(void) {/* sleep(); */}
//  vector 45 DEND0B
void    INT_DEND0B(void) {/* sleep(); */}
//  vector 46 DEND1A
void    INT_DEND1A(void) {/* sleep(); */}
//  vector 47 DEND1B
void    INT_DEND1B(void) {/* sleep(); */}
//  vector 48 Reserved

//  vector 49 Reserved

//  vector 50 Reserved

//  vector 51 Reserved

//  vector 52 ERI0
void    INT_ERI0(void) {
		if( ERI0Jump!=NULL ){
			ERI0Jump();
		}
}
//  vector 53 RXI0
void    INT_RXI0(void) {
		if( RXI0Jump!=NULL ){
			RXI0Jump();
		}
}
//  vector 54 TXI0
void    INT_TXI0(void) {
		if( TXI0Jump!=NULL ){
			TXI0Jump();
		}
}
//  vector 55 TEI0
void    INT_TEI0(void) {
		if( TEI0Jump!=NULL ){
			TEI0Jump();
		}
}
//  vector 56 ERI1
void    INT_ERI1(void) {
		if( ERI1Jump!=NULL ){
			ERI1Jump();
		}
}
//  vector 57 RXI1
void    INT_RXI1(void) {
		if( RXI1Jump!=NULL ){
			RXI1Jump();
		}
}
//  vector 58 TXI1
void    INT_TXI1(void) {
		if( TXI1Jump!=NULL ){
			TXI1Jump();
		}
}
//  vector 59 TEI1
void    INT_TEI1(void) {
		if( TEI1Jump!=NULL ){
			TEI1Jump();
		}
}

//  vector 60 ADI
void    INT_ADI(void) {/* sleep(); */}


//  vector Dummy
void    Dummy(void) {/* sleep(); */}




