/********************************************************************
*	【香港地下鉄向け自動列車放送制御装置】							*
*-------------------------------------------------------------------*
*	初期設定モジュール												*
*-------------------------------------------------------------------*
*	Author		TOA Corporation									*
*																	*
*	Revision	a00. 2000/06/27		K.Honda							*
*				a01. 2001/02/13		1M -> 4M RAM に伴い,
									起動時に２ｍＳ以上のウェイトを追加
*																	*
*********************************************************************/

/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	"iodefine.h"

#include	"table.h"

//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()

#pragma stacksize	4096

#pragma entry PowerON_Reset        

extern void main(void);

#ifdef __cplusplus
extern "C" {
#endif
extern void _INITSCT(void);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus				// Use SIM I/O
extern "C" {
#endif
extern void _INIT_IOLIB(void);
extern void _CLOSEALL(void);
#ifdef __cplusplus
}
#endif

//extern void srand(unsigned int);	// Remove the comment when you use rand()
//extern char *_s1ptr;				// Remove the comment when you use strtok()
		
#ifdef __cplusplus				// Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif
	
#pragma section ResetPRG

void PowerON_Reset(void);
void PowerON_Reset(void)
{ 
	or_ccr(0xC0);				// 全面割り込み禁止
	set_imask_ccr(1);

	P8.DDR = 0xFE;		// CS3 Enable

			// ２ｍＳ以上のウェイト
		ITU0.TCR.BYTE = 0;
		ITU0.TCR.BIT.TPSC = 2;		/* Φ／４クロック */
		ITU0.TIOR.BYTE = 0;			/* コンペアマッチによる出力禁止 */
		ITU0.TIER.BYTE = 0;

		ITU0.TCNT = 0;				/* カウンタークリア */
										/* 14.7456MHz -> Φ
										Φ／４ = 3.6864MHz
										0.27126uS
										2mS / 0.27126uS = 0x1CCC
									*/
		/** タイマースタート **/
		ITU.TSTR.BYTE = 0;
		ITU.TSTR.BIT.STR0 = 1;

		while( ITU0.TCNT<0x2000 )	// 2.2mS 程度
			;
		ITU.TSTR.BYTE = 0;

	_INITSCT();

	HardwareSetup();				// Use Hardware Setup

	_INIT_IOLIB();					// Use SIM I/O

	main();

	_CLOSEALL();					// Use SIM I/O
	
	sleep();
}

void Manual_Reset(void); 
void Manual_Reset(void)
{
}

//  vector 11 TRAP
void    INT_TRAP4(void) {
		long		l;
		int			i;

		DUALBOOT.address = 0;
		set_imask_ccr(1);
		i=2;
		for( l=0; l<1000000L; l++ ){
			i= i*2;
		}
		sleep();
}

