# ==========================================================================
#	◇◇◇　香港地下鉄自動放送　◇◇◇
# ==========================================================================
# Rules and Flags

.SUFFIXES: .hex .mot .obj .c .src

#-------------------------------------------
#                 ICC rules
#-------------------------------------------

# [[ H8 ]]
CC = ch38.exe
AS = asm38.exe
LN = optlnk38.exe
CONV = cnvs.exe

# [[ Compiler Option ]]
#CFLAGS = -cpu=300ha:24 -debug -list -show=object -chgincpath -pack=1 -lang=c -include=.\INC,..\COMMINC,..\DVA1BOOT\INC
CFLAGS = -cpu=300ha:24 -debug -list -show=object -chgincpath -pack=1 -lang=c -include=$(INC),$(COMMINC),$(BOOTINC)

# [[ Assambler Option ]]
AFLAGS = -cpu=300ha:24 -debug -nolist -chgincpath -errorpath

# [[ Linker Option ]]
LD64C	= -f v:\iccz80\lnk64 V:\iccz80\lnkz80
LD64CH	= -f v:\iccz80\lnk64h V:\icc\cl64180o 

# src -> obj using ICC Assenbler
{.\src}.src.obj:
	$(AS) $< $(AFLAGS) -object=$* 

# .c -> obj using ICC Compiler
{.\src}.c.obj:
	$(CC) $(CFLAGS) $< -object=$*.obj

#-------------------------------------------
#                 Directory
#-------------------------------------------

SRC		= .\src^\
OBJ		= .\obj^\
INC		= .\inc^\
BOOTINC	= .\inc^\
COMMINC = .\inc^\

#-------------------------------------------
#                 Making
#-------------------------------------------

PGM		=	DVAU1

A_OBJS	=	$(OBJ)lowlvl.obj

C_OBJS	=	$(OBJ)entry.obj $(OBJ)sbrk.obj \
		$(OBJ)dvamain.obj $(OBJ)dvainit.obj $(OBJ)dvaio.obj \
		$(OBJ)dvatms.obj $(OBJ)hdlc.obj $(OBJ)dosaccs3.obj $(OBJ)dvatime.obj $(OBJ)commlib.obj \
		$(OBJ)dvamente.obj

OBJS = $(A_OBJS) $(C_OBJS)

#
# OBJ －＞ MOT ファイル
#
$(PGM).mot	: $(OBJS) LINK.CMD
#	$(LN) -f LINK.CMD  $(LD64CH) -o $(PGM) -l $(PGM).map -t
#	$(LN) -f LINK.CMD  $(LD64C) -o $(PGM) -l $(PGM).map
	$(LN) -SubCommand=LINK.CMD
	$(CONV) ".\DVAU1.abs" ".\DVAU1.mot"

#起動プログラム
$(OBJ)entry.obj : $(SRC)entry.c

#システム供給
$(OBJ)sbrk.obj : $(SRC)sbrk.c $(BOOTINC)sbrk.h

#ファイルアクセス
$(OBJ)dosaccs3.obj : $(SRC)dosaccs3.c $(BOOTINC)dosaccs.h $(BOOTINC)fcntl.h

#ブートＲＯＭ呼び出し
$(OBJ)lowlvl.obj : $(SRC)lowlvl.src

#ＨＤＬＣ割り込み処理
$(OBJ)hdlc.obj : $(SRC)hdlc.c $(BOOTINC)iodefine.h $(INC)timer.h

#非同期通信処理
$(OBJ)commlib.obj : $(SRC)commlib.c $(BOOTINC)iodefine.h

#メインルーティン
$(OBJ)dvamain.obj : $(SRC)dvamain.c $(BOOTINC)iodefine.h $(COMMINC)table.h $(INC)timer.h

#初期設定
$(OBJ)dvainit.obj : $(SRC)dvainit.c $(BOOTINC)iodefine.h

#Ｉ／Ｏ処理
$(OBJ)dvaio.obj : $(SRC)dvaio.c $(BOOTINC)iodefine.h $(COMMINC)table.h

#ＴＭＳ通信処理
$(OBJ)dvatms.obj : $(SRC)dvatms.c $(BOOTINC)iodefine.h $(COMMINC)table.h $(INC)timer.h 

#タイマー割り込み処理
$(OBJ)dvatime.obj : $(SRC)dvatime.c $(BOOTINC)iodefine.h $(COMMINC)table.h $(INC)timer.h

#メンテナンス処理
$(OBJ)dvamente.obj : $(SRC)dvamente.c $(BOOTINC)iodefine.h $(COMMINC)table.h $(INC)timer.h $(BOOTINC)dosaccs.h $(BOOTINC)fcntl.h


