/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup();
#ifdef __cplusplus
}
#endif


/*
char        cDMAC0A_MAR[10];
int         iDMAC0B_MAR[10];
short       nDMAC1A_MAR[10];
long        lDMAC1B_MAR[10];
*/

void HardwareSetup()
{
	/*** CPU Mode3 ***/

	/**** ポート方向設定 ****/
		P4.DDR = 0;			/* P4 is Input( DIP-SW ) */
		P4.PCR.BYTE = 0;	/* P4 pullup is External */

		P6.DDR = 0x80;		/* P6 no use */

							/* P7 Input SCI0 status */

		P8.DDR = 0xFE;		/* P8 b4-b1=CS0-CS3, b0=IRQ0 */

		P9.DDR = 0xC0;		/* P9 b5=IRQ5, b4=IRQ4, b3=RxD1, b2=RxD0, b1=TxD1, b0=TxD0 */

		PA.DDR = 0xFF;		/* PA b7=A20, b6= , b5= , b4= , b3=DTR1, b2=RTS1, b1=DTR0, b0=RTS0 */

		PB.DDR = 0xFF;		/* PB b7=CPU2 Reset, b6=Slot-CS, b5=Slot-WP, b4=Slot-IORDA, b3=Slot-IOERA, b2=Slot-REG, b1=Slot-RESA, b0=Slot-Reset */

		SYSCR.BYTE = 0;
		SYSCR.BIT.SSBY  = 1;		/* Sleep 命令後、ソフトウェアスタンバイ */
		SYSCR.BIT.STS   = 7;		/* 使用禁止 */
		SYSCR.BIT.UE    = 1;		/* ユーザーレベル */
		SYSCR.BIT.NMIEG = 0;
		SYSCR.BIT.RAME  = 1;		/*内臓ＲＡＭ有効 */

		INTC.ISCR.BYTE = 0;
		INTC.ISCR.BIT.IRQ5SC = 0;	/* IRQ5 LowLevel */
		INTC.ISCR.BIT.IRQ4SC = 1;	/* IRQ4 HighLevel */
		INTC.ISCR.BIT.IRQ0SC = 1;	/* IRQ0 HighLevel */
		INTC.IER.BYTE = 0;
		INTC.IER.BIT.IRQ5E = 1;		/* IRQ5 Use */
		INTC.IER.BIT.IRQ4E = 1;		/* IRQ4 Use */
		INTC.IER.BIT.IRQ0E = 1;		/* IRQ0 Use */

		INTC.IPRA.BYTE = 0;
		INTC.IPRA.BIT.B3 = 1;  // Set WDT,RFSHC Priority Level 1

		INTC.IPRB.BYTE = 0;
}

