/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	"iodefine.h"

#include	"table.h"

//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()

#pragma stacksize	4096

#pragma entry PowerON_Reset        

extern void main(void);

#ifdef __cplusplus
extern "C" {
#endif
extern void _INITSCT(void);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus				// Use SIM I/O
extern "C" {
#endif
extern void _INIT_IOLIB(void);
extern void _CLOSEALL(void);
#ifdef __cplusplus
}
#endif

//extern void srand(unsigned int);	// Remove the comment when you use rand()
//extern char *_s1ptr;				// Remove the comment when you use strtok()
		
#ifdef __cplusplus				// Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif
	
#pragma section ResetPRG

void PowerON_Reset(void);
void PowerON_Reset(void)
{ 
	or_ccr(0xC0);				// ëSñ äÑÇËçûÇ›ã÷é~
	set_imask_ccr(1);

	P8.DDR = 0xFE;		// CS3 Enable

	_INITSCT();

	HardwareSetup();				// Use Hardware Setup

	_INIT_IOLIB();					// Use SIM I/O

	main();

	_CLOSEALL();					// Use SIM I/O
	
	sleep();
}

void Manual_Reset(void); 
void Manual_Reset(void)
{
}

//  vector 11 TRAP
void    INT_TRAP4(void) {
		long		l;
		int			i;

		DUALBOOT.address = 0;
		set_imask_ccr(1);
		i=2;
		for( l=0; l<1000000L; l++ ){
			i= i*2;
		}
		sleep();
}

