/***********************************************************************/
/*                                                                     */
/*  FILE        :vect.h                                                */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Definition of Vector                                  */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  




//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset 
extern void PowerON_Reset(void);                                                                                                                   
//;<<VECTOR DATA END (POWER ON RESET)>>
// 1 Reserved

// 2 Reserved

// 3 Reserved

// 4 Reserved

// 5 Reserved 

// 6 Reserved

// 7 NMI 
#pragma interrupt INT_NMI
extern void INT_NMI(void);
// 8 TRAP
#pragma interrupt INT_TRAP1
extern void INT_TRAP1(void);
// 9 TRAP
#pragma interrupt INT_TRAP2
extern void INT_TRAP2(void);
// 10 TRAP
#pragma interrupt INT_TRAP3
extern void INT_TRAP3(void);
// 11 TRAP
#pragma interrupt INT_TRAP4
extern void INT_TRAP4(void);
// 12 IRQ0
#pragma interrupt INT_IRQ0
extern void INT_IRQ0(void);
// 13 IRQ1
#pragma interrupt INT_IRQ1
extern void INT_IRQ1(void);
// 14 IRQ2
#pragma interrupt INT_IRQ2
extern void INT_IRQ2(void);
// 15 IRQ3
#pragma interrupt INT_IRQ3
extern void INT_IRQ3(void);
// 16 IRQ4
#pragma interrupt INT_IRQ4
extern void INT_IRQ4(void);
// 17 IRQ5
#pragma interrupt INT_IRQ5
extern void INT_IRQ5(void);
// 18 Reserved

// 19 Reserved

// 20 WOVI
#pragma interrupt INT_WOVI
extern void INT_WOVI(void);
// 21 CMI
#pragma interrupt INT_CMI
extern void INT_CMI(void);
// 22 Reserved

// 23 Reserved

// 24 IMIA0
#pragma interrupt INT_IMIA0
extern void INT_IMIA0(void);
// 25 IMIB0
#pragma interrupt INT_IMIB0
extern void INT_IMIB0(void);
// 26 OVI0
#pragma interrupt INT_OVI0
extern void INT_OVI0(void);
// 27 Reserved

// 28 IMIA1
#pragma interrupt INT_IMIA1
extern void INT_IMIA1(void);
// 29 IMIB1
#pragma interrupt INT_IMIB1
extern void INT_IMIB1(void);
// 30 OVI1
#pragma interrupt INT_OVI1
extern void INT_OVI1(void);
// 31 Reserved

// 32 IMIA2
#pragma interrupt INT_IMIA2
extern void INT_IMIA2(void);
// 33 IMIB2
#pragma interrupt INT_IMIB2
extern void INT_IMIB2(void);
// 34 OVI2
#pragma interrupt INT_OVI2
extern void INT_OVI2(void);
// 35 Reserved

// 36 IMIA3
#pragma interrupt INT_IMIA3
extern void INT_IMIA3(void);
// 37 IMIB3
#pragma interrupt INT_IMIB3
extern void INT_IMIB3(void);
// 38 OVI3
#pragma interrupt INT_OVI3
extern void INT_OVI3(void);
// 39 Reserved

// 40 IMIA4
#pragma interrupt INT_IMIA4
extern void INT_IMIA4(void);
// 41 IMIB4
#pragma interrupt INT_IMIB4
extern void INT_IMIB4(void);
// 42 OVI4
#pragma interrupt INT_OVI4
extern void INT_OVI4(void);
// 43 Reserved

// 44 DEND0A
#pragma interrupt INT_DEND0A
extern void INT_DEND0A(void);
// 45 DEND0B
#pragma interrupt INT_DEND0B
extern void INT_DEND0B(void);
// 46 DEND1A
#pragma interrupt INT_DEND1A
extern void INT_DEND1A(void);
// 47 DEND1B
#pragma interrupt INT_DEND1B
extern void INT_DEND1B(void);
// 48 Reserved

// 49 Reserved

// 50 Reserved

// 51 Reserved

// 52 ERI0
#pragma interrupt INT_ERI0
extern void INT_ERI0(void);
// 53 RXI0
#pragma interrupt INT_RXI0
extern void INT_RXI0(void);
// 54 TXI0
#pragma interrupt INT_TXI0
extern void INT_TXI0(void);
// 55 TEI0
#pragma interrupt INT_TEI0
extern void INT_TEI0(void);
// 56 ERI1
#pragma interrupt INT_ERI1
extern void INT_ERI1(void);
// 57 RXI1
#pragma interrupt INT_RXI1
extern void INT_RXI1(void);
// 58 TXI1
#pragma interrupt INT_TXI1
extern void INT_TXI1(void);
// 59 TEI1
#pragma interrupt INT_TEI1
extern void INT_TEI1(void);
// 60 ADI
#pragma interrupt INT_ADI
extern void INT_ADI(void);

// Dummy
#pragma interrupt Dummy
extern void Dummy(void);
