/***********************************************************************/
/*                                                                     */
/*  FILE        :intprg.c                                              */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Interrupt Program                                     */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  



#include    <machine.h>
#include    "vect.h"
#pragma section IntPRG
//  vector 1 Reserved

//  vector 2 Reserved

//  vector 3 Reserved

//  vector 4 Reserved

//  vector 5 Reserved 

//  vector 6 Reserved

//  vector 7 NMI 
void    INT_NMI(void) {/* sleep(); */}
//  vector 8 TRAP
void    INT_TRAP1(void) {/* sleep(); */}
//  vector 9 TRAP
void    INT_TRAP2(void) {/* sleep(); */}
//  vector 10 TRAP
void    INT_TRAP3(void) {/* sleep(); */}
//  vector 11 TRAP
void    INT_TRAP4(void) {/* sleep(); */}
//  vector 12 IRQ0
void    INT_IRQ0(void) {/* sleep(); */}
//  vector 13 IRQ1
void    INT_IRQ1(void) {/* sleep(); */}
//  vector 14 IRQ2
void    INT_IRQ2(void) {/* sleep(); */}
//  vector 15 IRQ3
void    INT_IRQ3(void) {/* sleep(); */}
//  vector 16 IRQ4
void    INT_IRQ4(void) {/* sleep(); */}
//  vector 17 IRQ5
void    INT_IRQ5(void) {/* sleep(); */}
//  vector 18 Reserved

//  vector 19 Reserved

//  vector 20 WOVI
void    INT_WOVI(void) {/* sleep(); */}
//  vector 21 CMI
void    INT_CMI(void) {/* sleep(); */}
//  vector 22 Reserved

//  vector 23 Reserved

//  vector 24 IMIA0
void    INT_IMIA0(void) {/* sleep(); */}
//  vector 25 IMIB0
void    INT_IMIB0(void) {/* sleep(); */}
//  vector 26 OVI0
void    INT_OVI0(void) {/* sleep(); */}
//  vector 27 Reserved

//  vector 28 IMIA1
void    INT_IMIA1(void) {/* sleep(); */}
//  vector 29 IMIB1
void    INT_IMIB1(void) {/* sleep(); */}
//  vector 30 OVI1
void    INT_OVI1(void) {/* sleep(); */}
//  vector 31 Reserved

//  vector 32 IMIA2
void    INT_IMIA2(void) {/* sleep(); */}
//  vector 33 IMIB2
void    INT_IMIB2(void) {/* sleep(); */}
//  vector 34 OVI2
void    INT_OVI2(void) {/* sleep(); */}
//  vector 35 Reserved

//  vector 36 IMIA3
void    INT_IMIA3(void) {/* sleep(); */}
//  vector 37 IMIB3
void    INT_IMIB3(void) {/* sleep(); */}
//  vector 38 OVI3
void    INT_OVI3(void) {/* sleep(); */}
//  vector 39 Reserved

//  vector 40 IMIA4
void    INT_IMIA4(void) {/* sleep(); */}
//  vector 41 IMIB4
void    INT_IMIB4(void) {/* sleep(); */}
//  vector 42 OVI4
void    INT_OVI4(void) {/* sleep(); */}
//  vector 43 Reserved

//  vector 44 DEND0A
void    INT_DEND0A(void) {/* sleep(); */}
//  vector 45 DEND0B
void    INT_DEND0B(void) {/* sleep(); */}
//  vector 46 DEND1A
void    INT_DEND1A(void) {/* sleep(); */}
//  vector 47 DEND1B
void    INT_DEND1B(void) {/* sleep(); */}
//  vector 48 Reserved

//  vector 49 Reserved

//  vector 50 Reserved

//  vector 51 Reserved

//  vector 52 ERI0
void    INT_ERI0(void) {/* sleep(); */}
//  vector 53 RXI0
void    INT_RXI0(void) {/* sleep(); */}
//  vector 54 TXI0
void    INT_TXI0(void) {/* sleep(); */}
//  vector 55 TEI0
void    INT_TEI0(void) {/* sleep(); */}
//  vector 56 ERI1
void    INT_ERI1(void) {/* sleep(); */}
//  vector 57 RXI1
void    INT_RXI1(void) {/* sleep(); */}
//  vector 58 TXI1
void    INT_TXI1(void) {/* sleep(); */}
//  vector 59 TEI1
void    INT_TEI1(void) {/* sleep(); */}
//  vector 60 ADI
void    INT_ADI(void) {/* sleep(); */}


//  vector Dummy
void    Dummy(void) {/* sleep(); */}

