/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	"iodefine.h"

//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()

#pragma stacksize	4096

#pragma entry PowerON_Reset        

extern void main(void);

#ifdef __cplusplus
extern "C" {
#endif
extern void _INITSCT(void);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus				// Use SIM I/O
extern "C" {
#endif
extern void _INIT_IOLIB(void);
extern void _CLOSEALL(void);
#ifdef __cplusplus
}
#endif

//extern void srand(unsigned int);	// Remove the comment when you use rand()
//extern char *_s1ptr;				// Remove the comment when you use strtok()
		
#ifdef __cplusplus				// Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif
	
#pragma section ResetPRG

void PowerON_Reset(void);
void PowerON_Reset(void)
{ 
	or_ccr(0xC0);				// 全面割り込み禁止
	set_imask_ccr(1);

	P8.DDR = 0xFE;		// CS3 Enable

	HardwareSetup();				// Use Hardware Setup

	_INITSCT();

	main();

	sleep();
}

void Manual_Reset(void); 
void Manual_Reset(void)
{
}


/** プログラムブート時のマップ **/
struct st_dualboot{
		unsigned long	address;		/* Boot Address */
		unsigned long	len;			/* Boot length */
		unsigned char	data[2030];		/* Boot Data */
		unsigned short	check_time;
		unsigned short	check_date;
		unsigned long	check_all_bytes;
		unsigned char	ack;			/*  0=Boot Request, 1=Initial Ack, 2=Data Ack, 3=Reboot Ack */
		unsigned char	request;		/*  0=None, 1=Initial, 2=Data, 3=Reboot */
};
#define DUALBOOT2   (*(volatile struct st_dualboot *)0x0C0000) /* Dual Port Address*/

//  vector 11 TRAP
void    INT_TRAP4(void) {
		long		l;
		int			i;

		set_imask_ccr(1);
		DUALBOOT2.ack = 0xFF;		/* HALTing */
		i=2;
		for( l=0; l<10000; l++ ){
			i= i*2;
		}
		sleep();
}

