/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.c                                                */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Program of sbrk                                       */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include <stdio.h>
#include "sbrk.h"

//const size_t _sbrk_size=		/* Specifies the minimum unit of	*/
								/* the defined heap area			*/ 

static  union  {
		long  dummy ;        /* Dummy for 4-byte boundary          */
		char heap[HEAPSIZE]; /* Declaration of the area managed   */
                             /*                           by sbrk */
 }heap_area ;

static  char  *brk=(char *)&heap_area;/* End address of area assigned     */

/**************************************************************************/
/*     sbrk:Data write							  						  */
/*	    Return value:Start address of the assigned area (Pass)	  		  */
/*	                 -1				    (Failure)	  					  */
/**************************************************************************/
char  *sbrk(size_t size)		   /* Assigned area size	  */
{
      char  *p;

      if(brk+size>heap_area.heap+HEAPSIZE) /* Empty area size		  */
	   return (char *)-1 ;

      p=brk ;				   /* Area assignment		  */
      brk += size ;			   /* End address update	  */
      return p ;
}
