/***********************************************************************/
/*                                                                     */
/*  FILE        :vecttbl.c                                             */
/*  DATE        :Thu, Jul 27, 2000                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :H8/3002                                               */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include    "vect.h"
		
#pragma section VECTTBL
void *RESET_Vectors[] = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset 
	PowerON_Reset                                                                                                                           
//;<<VECTOR DATA END (POWER ON RESET)>>
};
#pragma section INTTBL
void *INT_Vectors[] = {
	// 1 Reserved
	(void *) Dummy,
	// 2 Reserved
	(void *) Dummy,
	// 3 Reserved
	(void *) Dummy,
	// 4 Reserved
	(void *) Dummy,
	// 5 Reserved 
	(void *) Dummy,
	// 6 Reserved
	(void *) Dummy,
	// 7 NMI 
	(void *) INT_NMI,
	// 8 TRAP
	(void *) INT_TRAP1,
	// 9 TRAP
	(void *) INT_TRAP2,
	// 10 TRAP
	(void *) INT_TRAP3,
	// 11 TRAP
	(void *) INT_TRAP4,
	// 12 IRQ0
	(void *) INT_IRQ0,
	// 13 IRQ1
	(void *) INT_IRQ1,
	// 14 IRQ2
	(void *) INT_IRQ2,
	// 15 IRQ3
	(void *) INT_IRQ3,
	// 16 IRQ4
	(void *) INT_IRQ4,
	// 17 IRQ5
	(void *) INT_IRQ5,
	// 18 Reserved
	(void *) Dummy,
	// 19 Reserved
	(void *) Dummy,
	// 20 WOVI
	(void *) INT_WOVI,
	// 21 CMI
	(void *) INT_CMI,
	// 22 Reserved
	(void *) Dummy,
	// 23 Reserved
	(void *) Dummy,
	// 24 IMIA0
	(void *) INT_IMIA0,
	// 25 IMIB0
	(void *) INT_IMIB0,
	// 26 OVI0
	(void *) INT_OVI0,
	// 27 Reserved
	(void *) Dummy,
	// 28 IMIA1
	(void *) INT_IMIA1,
	// 29 IMIB1
	(void *) INT_IMIB1,
	// 30 OVI1
	(void *) INT_OVI1,
	// 31 Reserved
	(void *) Dummy,
	// 32 IMIA2
	(void *) INT_IMIA2,
	// 33 IMIB2
	(void *) INT_IMIB2,
	// 34 OVI2
	(void *) INT_OVI2,
	// 35 Reserved
	(void *) Dummy,
	// 36 IMIA3
	(void *) INT_IMIA3,
	// 37 IMIB3
	(void *) INT_IMIB3,
	// 38 OVI3
	(void *) INT_OVI3,
	// 39 Reserved
	(void *) Dummy,
	// 40 IMIA4
	(void *) INT_IMIA4,
	// 41 IMIB4
	(void *) INT_IMIB4,
	// 42 OVI4
	(void *) INT_OVI4,
	// 43 Reserved
	(void *) Dummy,
	// 44 DEND0A
	(void *) INT_DEND0A,
	// 45 DEND0B
	(void *) INT_DEND0B,
	// 46 DEND1A
	(void *) INT_DEND1A,
	// 47 DEND1B
	(void *) INT_DEND1B,
	// 48 Reserved
	(void *) Dummy,
	// 49 Reserved
	(void *) Dummy,
	// 50 Reserved
	(void *) Dummy,
	// 51 Reserved
	(void *) Dummy,
	// 52 ERI0
	(void *) INT_ERI0,
	// 53 RXI0
	(void *) INT_RXI0,
	// 54 TXI0
	(void *) INT_TXI0,
	// 55 TEI0
	(void *) INT_TEI0,
	// 56 ERI1
	(void *) INT_ERI1,
	// 57 RXI1
	(void *) INT_RXI1,
	// 58 TXI1
	(void *) INT_TXI1,
	// 59 TEI1
	(void *) INT_TEI1,
	// 60 ADI
	(void *) INT_ADI
};
